site:
  title: Serverless Workflow Guides
antora:
  extensions:
  - require: '@antora/lunr-extension'
content:
  sources:
    - url: https://github.com/amadhusu/test-action.git
      branches: HEAD
      start_path: serverlessworkflow
ui:
  bundle:
    url: ./antora/ui-bundle.zip
    snapshot: true
  supplemental_files: ./antora/supplemental-ui
asciidoc: 
  attributes: 
    linkattrs: ''
    toc: ~
