name: Serverless Workflow Guides

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [main]
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - 'README*'
jobs:
  build_site:
    name: "Building Serverless Workflow Documentation with Antora"
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: export DOCSEARCH_ENABLED=true
      - run: export DOCSEARCH_ENGINE=lunr
      - run: export NODE_PATH="$(npm -g root)"
      - run: npm -v
      - run: npm install
      - run: npx antora antora-playbook.yml --stacktrace
      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: test-action # e.g. 'my-project'
          directory: build/site # e.g. 'dist'
          gitHubToken: ${{ secrets.GH_TOKEN }}
